apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.customer.name }}-{{ .Values.product }}-config
  namespace: customer-{{ .Values.global.customer.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
data:
  config.env: |
    NODE_NAME=edge
    NODE_DESCRIPTION=Edge node
    DELTA_NODE_API=https://delta.estuary.tech
    DEAL_CHECK=600 # 10 minutes
    REPLICATION_FACTOR=3
    REPO=/storage/whypfs
    {{- $dbName := "edgedb" }}
    {{- $secretNamespace := printf "customer-%s" .Values.global.customer.name }}
    DB_NAME={{ $dbName }}
    {{- $decodedPassword := .Values.global.customer.edge_db_password | b64dec }}
    {{ printf "DB_DSN=postgres://edge:%s@edge.dbfws.%s/edgedb" $decodedPassword $secretNamespace }}
