{{- $sizeConfig := include "cpi-edge.getSizeConfig" . | fromYaml }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.customer.name }}-{{ .Values.product }}
  namespace: customer-{{ .Values.global.customer.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app: {{ .Values.global.customer.name }}-{{ .Values.product }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.global.customer.name }}-{{ .Values.product }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.customer.name }}-{{ .Values.product }}
      annotations:
        kubernetes.io/ingress-bandwidth: {{ $sizeConfig.ingressBandwidth }}
        kubernetes.io/egress-bandwidth: {{ $sizeConfig.egressBandwidth }}
    spec:
      containers:
      - name: {{ .Values.product }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        workingDir: /app
        command: ["/app/edge", "daemon"]
        #command: ["/bin/sh", "-c", "while true; do sleep 30; done"]
        # envFrom:
        #   - secretRef:
        #       name: {{ .Values.global.customer.name }}-{{ .Values.product }}-secret
        ports:
          - name: edge-http
            containerPort: 1313
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /ping
            port: edge-http
        resources:
          limits:
            cpu: "{{ $sizeConfig.cpuLimit }}"
            memory: "{{ $sizeConfig.memoryLimit }}"
          requests:
            cpu: "{{ $sizeConfig.cpuRequest }}"
            memory: "{{ $sizeConfig.memoryRequest }}"
        volumeMounts:
          - name: storage
            mountPath: /storage
          - name: env-file
            mountPath: /app/.env
            subPath: config.env
      volumes:
      - name: env-file
        configMap:
          name: {{ .Values.global.customer.name }}-{{ .Values.product }}-config
      - name: storage
        persistentVolumeClaim:
          claimName: {{ .Values.global.customer.name }}-{{ .Values.product }}-storage
