apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.customer.name }}-{{ .Values.product }}-config
  namespace: customer-{{ .Values.global.customer.name }}
data:
  config.env: |
    NODE_NAME=edge
    NODE_DESCRIPTION=Edge node
    DB_NAME=edge-urdb
    DELTA_NODE_API=https://node.delta.store
    DEAL_CHECK=600 # 10 minutes
    REPLICATION_FACTOR=3
    REPO=/storage/whypfs